name: vocalink
description: Voice to Action App
version: 1.0.0+1

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^3.8.5

  # Voice input
  speech_to_text: 7.1.0

  # Fonts and UI
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.4.0

  # Contact access
  flutter_contacts: ^1.1.6

  # Permissions
  permission_handler: ^12.0.1
  string_similarity: ^2.0.0
  # Battery info
  battery_plus: ^5.0.3

  # External actions
  url_launcher: ^6.1.14
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
